name: CI-Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: Otus.Teaching.PromoCodeFactory.WebHost
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj          
      
      - name: Build project
        run: dotnet build ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj -c Release -o content

      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: content
